<?php

namespace srag\Plugins\AutoDeactivation\Job;

use srag\Plugins\AutoDeactivation\User\Repository as UserRepository;
use srag\Plugins\AutoDeactivation\Utils\AutoDeactivationTrait;
use ilAutoDeactivationPlugin;
use ilCronJob;
use ilCronJobResult;
use srag\DIC\AutoDeactivation\DICTrait;

/**
 * Class Job
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AutoDeactivation\Job
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support@studer-raimann.ch>
 */
class Job extends ilCronJob
{

    use DICTrait;
    use AutoDeactivationTrait;
    const CRON_JOB_ID =  ilAutoDeactivationPlugin::PLUGIN_ID . "_cron";
    const PLUGIN_CLASS_NAME = ilAutoDeactivationPlugin::class;


    /**
     * Job constructor
     */
    public function __construct()
    {

    }


    /**
     * @inheritDoc
     */
    public function getId() : string
    {
        return self::CRON_JOB_ID;
    }


    /**
     * @inheritDoc
     */
    public function getTitle() : string
    {
        return ilAutoDeactivationPlugin::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function getDescription() : string
    {
        return "";
    }


    /**
     * @inheritDoc
     */
    public function hasAutoActivation() : bool
    {
        return true;
    }


    /**
     * @inheritDoc
     */
    public function hasFlexibleSchedule() : bool
    {
        return true;
    }


    /**
     * @inheritDoc
     */
    public function getDefaultScheduleType() : int
    {
        return self::SCHEDULE_TYPE_DAILY;
    }


    /**
     * @inheritDoc
     */
    public function getDefaultScheduleValue()/*:?int*/
    {
        return null;
    }


    /**
     * @inheritDoc
     */
    public function run() : ilCronJobResult
    {
        $result = new ilCronJobResult();

        $user_repository = new UserRepository(self::dic()->dic(), self::autoDeactivation()->config());


        $result->setStatus(ilCronJobResult::STATUS_OK);

        return $result;
    }
}
