<?php

namespace srag\Plugins\AutoDeactivation\Job;

use srag\Plugins\AutoDeactivation\Utils\AutoDeactivationTrait;
use srag\DIC\AutoDeactivation\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AutoDeactivation\Job
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support@studer-raimann.ch>
 */
final class Repository
{

    use DICTrait;
    use AutoDeactivationTrait;
    const PLUGIN_CLASS_NAME = ilAutoDeactivationPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @internal
     */
    public function dropTables()/*: void*/
    {

    }


    /**
     * @return Factory
     */
    public function factory() : Factory
    {
        return Factory::getInstance();
    }


    /**
     * @internal
     */
    public function installTables()/*: void*/
    {

    }
}
