<?php

namespace srag\Plugins\AutoDeactivation\Config;

use srag\Plugins\AutoDeactivation\Utils\AutoDeactivationTrait;
use ilAutoDeactivationConfigGUI;
use ilAutoDeactivationPlugin;
use srag\ActiveRecordConfig\AutoDeactivation\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AutoDeactivation\Config
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support@studer-raimann.ch>
 */
final class Factory extends AbstractFactory
{

    use AutoDeactivationTrait;
    const PLUGIN_CLASS_NAME = ilAutoDeactivationPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @param ilAutoDeactivationConfigGUI $parent
     *
     * @return ConfigFormGUI
     */
    public function newFormInstance(ilAutoDeactivationConfigGUI $parent) : ConfigFormGUI
    {
        $form = new ConfigFormGUI($parent);

        return $form;
    }
}
