<?php

namespace srag\Plugins\AutoDeactivation\Config;

use ilAutoDeactivationPlugin;
use srag\ActiveRecordConfig\AutoDeactivation\Config\AbstractFactory;
use srag\ActiveRecordConfig\AutoDeactivation\Config\AbstractRepository;
use srag\ActiveRecordConfig\AutoDeactivation\Config\Config;
use srag\Plugins\AutoDeactivation\Utils\AutoDeactivationTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AutoDeactivation\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use AutoDeactivationTrait;
    const PLUGIN_CLASS_NAME = ilAutoDeactivationPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @inheritDoc
     *
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }


    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilAutoDeactivationPlugin::PLUGIN_ID . "_config";
    }


    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::KEY_LOCAL_USERS_ONLY    => Config::TYPE_STRING,
            ConfigFormGUI::KEY_THRESHOLD_IN_DAYS   => Config::TYPE_INTEGER,
            ConfigFormGUI::KEY_DAYS_WARNING        => Config::TYPE_INTEGER,
            ConfigFormGUI::KEY_NOTIFICATION_EMAILS => Config::TYPE_STRING,
        ];
    }
}
