<?php

namespace srag\Plugins\AutoDeactivation\Utils;

use srag\Plugins\AutoDeactivation\Repository;

/**
 * Trait AutoDeactivationTrait
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\AutoDeactivation\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support@studer-raimann.ch>
 */
trait AutoDeactivationTrait
{

    /**
     * @return Repository
     */
    protected static function autoDeactivation() : Repository
    {
        return Repository::getInstance();
    }
}
